#!/bin/bash


# ******** WARNING: Unix CR/LF mode must be used when editing this file ****************


IPA_FILE=$1
TMP_FOLDER=/tmp/inst2
PAYLOAD_FOLDER=$TMP_FOLDER/Payload


echo "------------- UNZIP the IPA bundle -------------"
unzip -X -K -qq -o "$IPA_FILE" -d  $TMP_FOLDER
if [ $? -ne 0 ]
then
  echo "UNZIP command failed!"
  exit 1
fi


echo "------------- Set attributes to directories and executables -------------"
chmod 0755 $PAYLOAD_FOLDER -R
if [ $? -ne 0 ]
then
  echo "Error setting files attributes!"
  exit 1
fi


echo "------------- Get application's folder name -------------"
# Note: Just use the last folder it found
for FF in "$(ls $PAYLOAD_FOLDER)"; do
  APP_FOLDER="$FF"
done

echo "Application folder found was: $APP_FOLDER"


echo "------------- Remove destination folder if already exists -------------"
if [ -d /Applications/_$APP_FOLDER ];
then
  rm -f -r "/Applications/$APP_FOLDER"
  if [ $? -ne 0 ]
  then
    echo "Error deleting destination folder!"
    exit 1
  fi
fi


echo "------------- Move IPA bundle to its destination folder -------------"
mv -v -f "$PAYLOAD_FOLDER/$APP_FOLDER" "/Applications/_$APP_FOLDER"
if [ $? -ne 0 ]
then
  echo "Error moving IPA bundle files!"
  exit 1
fi


echo "------------- Remove temporal files and folder -------------"
rm -f -r $TMP_FOLDER/*
if [ $? -ne 0 ]
then
  echo "Error removing temporal files and folder!"
  exit 1
fi


echo "------------- OK exit -------------"
exit 0
